apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec: 
      containers:
      - name: homebridge
        image: oznu/homebridge:latest
        ports:
        - containerPort: 8581
        volumeMounts:
        - name: homebridge
          mountPath: /homebridge
      volumes:
      - name: homebridge
        hostPath:
          path: /home/jacob/repos/desk/data/homebridge
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge
spec:
  type: NodePort
  ports:
  - port: 8581
    targetPort: 8581
    nodePort: 30001
  selector:
    app: homebridge